
services:
  scraping_service:
    build: ./nse_scraper
    container_name: nse_scraper_app
    env_file:
      - .env  

  flask_app:
    build: ./server
    container_name: flask_servers
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - app_network

networks:
  app_network:
