services:
  scraping_service:
    build: ./nse_scraper
    container_name: nse_scraper_app
    env_file:
      - .env  

  flask_app:
    build: ./server
    container_name: flask_servers
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: vite_frontend
    ports:
      - "5173:5173"
    depends_on:
      - flask_app
    networks:
      - app_network
    environment:
      - WDS_SOCKET_PORT=0
    volumes:
      - ./frontend:/app  # Sync local frontend files
      - /app/node_modules  # Prevent overwriting node_modules inside the container


networks:
  app_network:
