version: '3.8'

services:
  app:
    build: .
    container_name: nse_scraper_app
    restart: always
    depends_on:
      - mysql_db
    env_file:
      - .env  # Load environment variables securely
    volumes:
      - .:/app
    networks:
      - app_network

  mysql_db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
